services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/html:/usr/share/nginx/html:ro
    depends_on:
      - python-ai-core
    networks:
      - titan-net

  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - titan-net

  python-ai-core:
    build:
      context: ./python_ai_core
    ports:
      - "8080:8080"
    volumes:
      - .:/app/data # Mount the repo root so we can access CSVs directly
    depends_on:
      - redis-cache
    environment:
      - REDIS_URL=redis://redis-cache:6379
    networks:
      - titan-net

networks:
  titan-net:
    driver: bridge
